### ISSUE TITLE
新機能の提案：リンクの形状について

### ISSUE THREAD

**Issue by halka9000stg** [wakufactory/MDG#2]
リンクのラインの形状(◟か└か＼か：先端ブロック(x1,y1)終端ブロック(x2,y2)の値がx1≠x2かつy1≠y2のとき)やリンクの先端の先の形状(＞か▷かなど)も設定できるようにしても良さそうだと思います.

(ps.リンクの途中から新たなリンクを発生させる機能とか....

**Comment by halka9000stg** [comment]
なお、psに記載のものは現状、custom.css内に以下のような記述をすることで対応。
```css
div.mdg .box.none{
	width: 0;
	height: 0;
	position: absolute;
	border: none;
	background-color: transparent;
	line-height:1.5em ;
	padding:0;
	box-sizing:border-box;
	cursor:move;
}
```
